// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrxGFh_ewEJeZOcI1KTmM5prL3ugP6dec',
    appId: '1:88309537787:web:a27a4cc45b1a990ee0895e',
    messagingSenderId: '88309537787',
    projectId: 'resturant-f093a',
    authDomain: 'resturant-f093a.firebaseapp.com',
    storageBucket: 'resturant-f093a.appspot.com',
    measurementId: 'G-2P2D1N9D5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_DIU9Kv8QLMrOsQKKOTzP80KRRtgoXLc',
    appId: '1:88309537787:android:5572c66b5eb19790e0895e',
    messagingSenderId: '88309537787',
    projectId: 'resturant-f093a',
    storageBucket: 'resturant-f093a.appspot.com',
    authDomain: 'resturant-f093a.firebaseapp.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKETi5rwVsda8GqaDJr49SdvAcwsrHH1w',
    appId: '1:88309537787:ios:e9c361e409e6a743e0895e',
    messagingSenderId: '88309537787',
    projectId: 'resturant-f093a',
    storageBucket: 'resturant-f093a.appspot.com',
    iosBundleId: 'com.sixamtech.stackFood',
    authDomain: 'resturant-f093a.firebaseapp.com',
  );
}
